# Numpy Questions

### Q.1) Create a numpy array in python?

In [2]:
import numpy as np

In [5]:
l1 = [1,2,3]
arr = np.array(l1, dtype = float)
arr

array([1., 2., 3.])

### Q.2) Write a program that takes in a NumPy array and returns its mean?

In [8]:
mean = np.mean(arr)
mean

2.0

### Q.3) Write a program that takes in a NumPy array and returns its shape?

In [13]:
l2 = [[1,2], [2,3], [3,4]]
arr2 = np.array(l2)
shape = np.shape(arr)
shape2 = np.shape(arr2)
shape2

(3, 2)

### Q.4) How can we convert a list into numpy array?

### Q.5) Creates a NumPy array filled with zeros of 3X3 size?

In [16]:
zeroMatrix = np.zeros((3,3), dtype = int)
zeroMatrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Q.6)  Creates a NumPy array filled with ones of mXn size?

In [18]:
n = int(input())
m = int(input())

zeroMatrix = np.ones((m,n), dtype = int)
zeroMatrix

3
4


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Q.7) Creates a NumPy array filled with random values between 0 and 1.

In [21]:
random_array = np.random.rand(3, 3)
random_array

ValueError: low >= high

### Q.8)  Creates a NumPy array with a range of values?

### Q.9) How to reshape a NumPy array to a new shape?

### Q.10) Computes the sum of all the elements in a NumPy array?

### Q.11) Computes the standard deviation of all the elements in a NumPy array.

### Q.12) Computes the dot product of two NumPy arrays.


### Q.13) Create a 2D NumPy array with shape (3, 3) containing all zeros?

### Q.14) Create a 1D numpy array containing the values from -10 to 10, with a step of 2.


### Q.15) Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, set all values in the first row to 0.

### Q.16) Create a 1D numpy array containing the values from 0 to 9. Then, create a new array containing the values squared.

### Q.17) Create a 1D numpy array containing the values from 1 to 10. Then, extract all even values from the array.

### Q.18) Create a 1D numpy array containing the values from 1 to 10. Then, extract all odd values from the array.

### Q.19)Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, compute the mean of each row.

In [32]:
# np.random.randint(0,1, (3, 3))
random_array = np.random.rand(3,3)
random_array
for i in random_array:
    print(np.mean(i))

0.1779656359713009
0.23678938658334817
0.48256536253178545


### Q.20) How to split numpy array into 3 parts?
#### arr = np.array([1, 2, 3, 4, 5, 6])

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_array = np.array_split(arr, 3)
split_array

[array([1, 2]), array([3, 4]), array([5, 6])]